name: Deploy
on:
  workflow_dispatch:
  push: 
    branches: main

jobs: 
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v4

            - name: set up Go Environment
              uses: actions/setup-go@v5
              with:
                go-version: "1.21.0"

            - name: Build Go Project
              run: go build -o ./bin/app ./cmd/

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: reyhanmichiels/aquafarm:latest

            - name: deploy 
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USERNAME }}
                password: ${{ secrets.EC2_SSH_PASSWORD }}
                port: ${{ secrets.EC2_SSH_PORT }}
                script: |
                  sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
                  sudo docker pull reyhan/aquafarm:latest
                  sudo docker compose --env-file .env down
                  sudo docker compose --env-file .env up -d
