name: debug

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"

      - name: Prepare environment
        run: |
          echo ls before fill
          ls -a
          echo ${{ secrets.ENV }} >> .env
          echo .env value
          cat .env
          echo ls after fill
          ls -a

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        run: |
          ls -a
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker buildx build . -t reyhan/aquafarm:latest --push

      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull reyhan/aquafarm:latest
            sudo docker compose --env-file .env down
            sudo docker compose --env-file .env up -d
