name: debug

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"

      - name: Prepare environment
        run: |
          echo ls before fill
          ls
          echo ${{ secrets.ENV }} >> .env
          cat .env
          echo ls after fill
          ls
      - name: build_docker_image
        run: |
          ls
          docker build .
