name: test-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"

      - name: test
        run: go test ./... --cover

      - name: build
        run: go build -o ./bin/app ./cmd